-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

-- força GBM no NVIDIA DRM e GL desktop

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty"

local fileManager = "thunar"

local menu = "hyprlauncher"

local scratch = "~/.local/bin/scratch"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:



















--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("AQ_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 1,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.active_border = rgba(458588ff) rgba(d65d0eff) 45deg
        -- col.inactive_border = rgba(504945ff)
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(3d59a1ff)", "rgba(414868ff)" }, angle = 45 },
            inactive_border = { colors = { "rgba(3d59a1ff)", "rgba(414868ff)" }, angle = 45 },
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 0,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.95,
        inactive_opacity = 0.7,
        shadow = {
            enabled = true,
            range = 50,
            render_power = 10,
            color = "rgba(24283bee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 5,
            passes = 1,
            vibrancy = 0.1696,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "altgr-intl",
        kb_model = "",
        kb_options = "caps:escape",
        kb_rules = "",
        repeat_delay = 300,
        repeat_rate = 50,
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- # https://wiki.hyprland.org/Configuring/Variables/#gestures

-- gestures {

--     workspace_swipe = false

-- }

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("hyprlauncher"))

-- bind = $mainMod, P, pseudo, # dwindle # What is this even for?

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

local reload = "hyprctl reload"

local clipboard_history = "cliphist list| hyprlauncher --dmenu| cliphist decode| wl-copy"

local screenshot = "~/.local/bin/print_screen"

local power_menu = "~/.config/scripts/power"

local brightness = "~/.config/scripts/brightness"

local idle_inhibit = "~/.config/scripts/idle"

local quick_access_terminal = "kitten quick-access-terminal"

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("~/.local/bin/print_screen"))

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("obsidian"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("kitten quick-access-terminal"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.exec_cmd("~/.local/bin/scratch"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| hyprlauncher --dmenu| cliphist decode| wl-copy"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("~/.config/scripts/power"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("~/.config/scripts/brightness"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.exec_cmd("~/.config/scripts/idle"))

-- Define o atalho para entrar no modo "browser" (ex.: $mod+b)

hl.bind(mainMod .. " + " .. "b", hl.dsp.submap("browser"))

-- Submapa "browser"

hl.define_submap("browser", function()
    -- help
    hl.bind("h", hl.dsp.exec_cmd("~/.config/hypr/scripts/zen_profiles.sh"))
    -- Atalhos para abrir perfis do Zen Browser
    hl.bind("p", hl.dsp.exec_cmd("zen-browser -P Pessoal"))
    hl.bind("p", hl.dsp.submap("reset"))
    hl.bind("b", hl.dsp.exec_cmd("zen-browser -P Balanças SMART"))
    hl.bind("b", hl.dsp.submap("reset"))
    hl.bind("g", hl.dsp.exec_cmd("zen-browser -P GPT"))
    hl.bind("g", hl.dsp.submap("reset"))
    hl.bind("u", hl.dsp.exec_cmd("zen-browser -P Mateus - UFG"))
    hl.bind("u", hl.dsp.submap("reset"))
    hl.bind("w", hl.dsp.exec_cmd("zen-browser -P Work - Pacto"))
    hl.bind("w", hl.dsp.submap("reset"))
    hl.bind("z", hl.dsp.exec_cmd("zen-browser -P Whatsapp"))
    hl.bind("z", hl.dsp.submap("reset"))
    hl.bind("SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("zen-browser -P Mateus - Trabalho"))
    hl.bind("W", hl.dsp.submap("reset"))
    -- Sair do modo "browser" e voltar ao padrão
    hl.bind(mainMod .. " + " .. "b", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("Escape", hl.dsp.submap("reset"))
    -- Fim do submapa
end)


-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "M", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.window.move({ workspace = "special:magic" }))

-- Special workspace (spotify)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("spotify"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:spotify" }))

hl.bind(mainMod .. " + " .. "I", hl.dsp.workspace.toggle_special("discord"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.window.move({ workspace = "special:discord" }))

hl.bind(mainMod .. " + " .. "W", hl.dsp.workspace.toggle_special("whatsapp"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.window.move({ workspace = "special:whatsapp" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "LEFT", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "RIGHT", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "UP", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "DOWN", hl.dsp.window.swap({ direction = "down" }))

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- Ignore maximize requests

hl.window_rule({
    name  = "nomaximize_1",
    match = {
        class = ".*",
    },
    -- TODO: review rule: "nomaximize 1"
})

-- Fix XWayland issues

hl.window_rule({
    name  = "nofocus_1",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
})

-- SwayNC

hl.window_rule({
    name  = "opacity_1",
    match = {
        class = "^(swaync)$",
    },
    opacity = 1,
})

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(swaync)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(swaync)$",
    },
    center = 1,
})

-- Special Workspaces

hl.window_rule({
    name  = "workspace_special_sp",
    match = {
        class = "^(spotify)$",
    },
    workspace = "special:spotify silent",
})

hl.window_rule({
    name  = "workspace_special_di",
    match = {
        class = "^(discord)$",
    },
    workspace = "special:discord silent",
})

hl.window_rule({
    name  = "workspace_special_wh",
    match = {
        class = "^(whatsdesk)$",
    },
    workspace = "special:whatsapp silent",
})

-- Standard Workspaces

hl.window_rule({
    name  = "workspace_10_silent",
    match = {
        title = "^(btop).*",
    },
    workspace = "10 silent",
})

hl.window_rule({
    name  = "workspace_1_silent",
    match = {
        title = "^(main-terminal).*",
    },
    workspace = "1 silent",
})

-- Scratchpad

hl.window_rule({
    name  = "float_1",
    match = {
        title = "^(scratch)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "size_800_800",
    match = {
        title = "^(scratch)$",
    },
    size = "800 800",
})

hl.window_rule({
    name  = "center_1",
    match = {
        title = "^(scratch)$",
    },
    center = 1,
})

-- Layer Rules (New syntax requires value 1)

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    }
    -- ignorezero = 1,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("kanshi &")
    hl.exec_cmd("hyprlauncher --daemon")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprctl setcursor catppuccin-mocha-dark 18")
    hl.exec_cmd("spotify-launcher")
    hl.exec_cmd("discord")
    hl.exec_cmd("whatsdesk")
    hl.exec_cmd("hyprctl dispatch exec [monitor:eDP-1; workspace 1 silent] ghostty --title=main-terminal -e zsh -c 'tmux; zsh'")
    hl.exec_cmd("hyprctl dispatch exec [workspace 3 silent] zen-browser --P Pessoal")
    hl.exec_cmd("wl-paste --type text --watch cliphist store -max-items 100")
    hl.exec_cmd("wl-paste --type image --watch cliphist store -max-items 100")
    hl.exec_cmd("wl-clip-persist --clipboard both")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
