#!/usr/bin/env bash

STATE_FILE="$HOME/.brightness_menu_last"

if [ -f "$STATE_FILE" ]; then
    LAST_CHOSEN=$(cat "$STATE_FILE")
else
    LAST_CHOSEN=""
fi

OPTIONS=(
    "󰃞"
    "󰃟"
    "󰃠"
    ""
    ""
)

while true; do
    CHOSEN=$(printf "%s\n" "${OPTIONS[@]}" | hyprlauncher --dmenu)

    [ -n "$CHOSEN" ] && echo "$CHOSEN" > "$STATE_FILE"

    LAST_CHOSEN="$CHOSEN"

    case "$CHOSEN" in
        "") brightnessctl set 10%- ;;
        "") brightnessctl set +10% ;;
        "󰃞") brightnessctl set 25%; break ;;
        "󰃟") brightnessctl set 50%; break ;;
        "󰃠") brightnessctl set 100%; break ;;
        *) break ;;
    esac
done
