#!/usr/bin/env bash

OPTIONS=(
  ""
  ""
)

CHOSEN=$(printf "%s\n" "${OPTIONS[@]}" | hyprlauncher --dmenu)

case "$CHOSEN" in
  "")  systemd-inhibit --what=idle --who="Manual Inhibit" --why="Watching video" --mode=block sleep infinity & echo $! > ~/.hypridle_inhibit.pid ;;
  "")  kill $(cat ~/.hypridle_inhibit.pid) && rm ~/.hypridle_inhibit.pid ;;
esac
