#!/usr/bin/env bash

OPTIONS=(
  ""
  ""
  ""
  ""
  ""
)

CHOSEN=$(printf "%s\n" "${OPTIONS[@]}" | hyprlauncher --dmenu)

case "$CHOSEN" in
  "")  systemctl poweroff   ;;
  "")  systemctl reboot     ;;
  "")  $HOME/.config/scripts/lock & systemctl suspend    ;;
  "")  $HOME/.config/scripts/lock    ;;
  "")  hyprctl dispatch exit         ;;
esac
