#!/usr/bin/env bash

OPTIONS=(
  ""
  ""
  ""
  ""
  ""
)

CHOSEN=$(printf "%s\n" "${OPTIONS[@]}" \
         | rofi -dmenu -i -theme simplemenu.rasi -p "")

case "$CHOSEN" in
  "")  systemctl poweroff   ;;
  "")  systemctl reboot     ;;
  "")  $HOME/.config/scripts/lock & systemctl suspend    ;;
  "")  $HOME/.config/scripts/lock    ;;
  "")  hyprctl dispatch exit         ;;
esac
