set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-restore 'X'
# Theme

set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @powerkit_theme 'tokyo-night'
set -g @powerkit_theme_variant 'night'
set -g @powerkit_session_icon 'auto'

set -g @continuum-restore 'on'

# Good navigation
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# navigate windows with Ctrl Alt l and h
bind -n M-H previous-window
bind -n M-L next-window

# new pane with Ctrl N
bind -n C-p split-window -h
bind -n C-o split-window -v
bind -n C-n new-window

# navigate panes with Ctrl Alt l and h
bind -n C-l select-pane -R
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U

# shame on me
set -g mouse on

# toggle split
bind-key -n 'C-\' run-shell -b "${HOME}/.local/bin/tmux-toggle-term.sh"

run '~/.tmux/plugins/tpm/tpm'
